DATE FRUIT CLASSIFICATION USING ANN

In [1]:
# Importing Required Libraries / Packages
import pandas as pd
import numpy as np

In [2]:
# Loading Dataset 

df = pd.read_csv("DateFruit_Dataset.csv")

In [3]:
df.head() # 34 Features and 1 category

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI

In [4]:
# Looking for any possible null values
df.isnull().sum()

AREA             0
PERIMETER        0
MAJOR_AXIS       0
MINOR_AXIS       0
ECCENTRICITY     0
EQDIASQ          0
SOLIDITY         0
CONVEX_AREA      0
EXTENT           0
ASPECT_RATIO     0
ROUNDNESS        0
COMPACTNESS      0
SHAPEFACTOR_1    0
SHAPEFACTOR_2    0
SHAPEFACTOR_3    0
SHAPEFACTOR_4    0
MeanRR           0
MeanRG           0
MeanRB           0
StdDevRR         0
StdDevRG         0
StdDevRB         0
SkewRR           0
SkewRG           0
SkewRB           0
KurtosisRR       0
KurtosisRG       0
KurtosisRB       0
EntropyRR        0
EntropyRG        0
EntropyRB        0
ALLdaub4RR       0
ALLdaub4RG       0
ALLdaub4RB       0
Class            0
dtype: int64

In [5]:
df.shape

(898, 35)

In [6]:
# Dropping Class and making it as output
x = df.drop("Class", axis = 1)
y = df["Class"]

In [7]:
x.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,SkewRB,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,0.6019,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,0.4134,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,0.9183,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,1.8028,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,0.8865,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666

In [8]:
y

0      BERHI
1      BERHI
2      BERHI
3      BERHI
4      BERHI
       ...
893    SOGAY
894    SOGAY
895    SOGAY
896    SOGAY
897    SOGAY
Name: Class, Length: 898, dtype: str

In [9]:
# Differernt Categories present in Class
df["Class"].unique()

<StringArray>
['BERHI', 'DEGLET', 'DOKOL', 'IRAQI', 'ROTANA', 'SAFAVI', 'SOGAY']
Length: 7, dtype: str

As it can be seen that there are 7 categories in the o/p, that means there will be 7 neurons in output layer.

In [10]:
# Encoding the Output from Strings to numeric
from sklearn.preprocessing import StandardScaler, LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [11]:
# Splitting data into train test split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.2, random_state=42)

In [12]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [13]:
# Scaling Features Because there is a big differernce in the values of features.

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

ANN

In [14]:
import torch 
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

In [15]:
# Coverting Data Points to Tensors
x_train_tensor = torch.tensor(x_train_scaled, dtype = torch.float32) 
y_train_tensor = torch.tensor(y_train, dtype = torch.long) 


x_test_tensor = torch.tensor(x_test_scaled, dtype = torch.float32)
y_test_tensor = torch.tensor(y_test, dtype = torch.long)

In [16]:
# Creating Dataset with tensors

train_df = TensorDataset(x_train_tensor,y_train_tensor)
test_df = TensorDataset(x_test_tensor,y_test_tensor)

In [17]:
# Creating Data Loader to fetch data from tensors

train_loader = DataLoader(train_df, batch_size = 32, shuffle = True)
test_loader = DataLoader(test_df, batch_size = 32)

BUILDING MODEL

In [18]:
class ANN(nn.Module):
    def __init__ (self):
        super(ANN, self).__init__()
        self.model = nn.Sequential(
            # 1st Hidden layer
            nn.Linear(x.shape[1],64),
            nn.ReLU(),
            # 2nd Hidden Layer
            nn.Linear(64,64),
            nn.ReLU(),
            # Output Layer
            nn.Linear(64,7)
        )
    def forward(self, x):
        return self.model(x)

In [19]:
model = ANN()

# Loss and Optimization
criteria = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters())

In [ ]:
# Training the Model/Neural Network

epochs = 100
for epoch in range (epochs):
    model.train() # Model in training mode

    running_loss = 0.0
    for xb, yb in train_loader:
        optimizer.zero_grad()
        outputs = model(xb)
        loss = criteria(outputs, yb)
        loss.backward()
        optimizer.step()

        running_loss += loss
    train_loss = running_loss/len(train_loader)
    print(f"epoch = {epoch+1}/{epochs}, loss = {train_loss}")

epoch = 1/100, loss = 1.702654242515564
epoch = 2/100, loss = 1.0874782800674438
epoch = 3/100, loss = 0.7632845044136047
epoch = 4/100, loss = 0.5820318460464478
epoch = 5/100, loss = 0.4709184765815735
epoch = 6/100, loss = 0.4051792323589325
epoch = 7/100, loss = 0.35857880115509033
epoch = 8/100, loss = 0.32315346598625183
epoch = 9/100, loss = 0.2886103093624115
epoch = 10/100, loss = 0.2706083059310913
epoch = 11/100, loss = 0.24726206064224243
epoch = 12/100, loss = 0.23781564831733704
epoch = 13/100, loss = 0.22081661224365234
epoch = 14/100, loss = 0.21434830129146576
epoch = 15/100, loss = 0.19615386426448822
epoch = 16/100, loss = 0.1838277131319046
epoch = 17/100, loss = 0.17441008985042572
epoch = 18/100, loss = 0.17567278444766998
epoch = 19/100, loss = 0.1663261353969574
epoch = 20/100, loss = 0.16520914435386658
epoch = 21/100, loss = 0.15507322549819946
epoch = 22/100, loss = 0.15139949321746826
epoch = 23/100, loss = 0.15760697424411774
epoch = 24/100, loss = 0.14797726273536682
epoch = 25/100, loss = 0.13730068504810333
epoch = 26/100, loss = 0.1313653439283371
epoch = 27/100, loss = 0.13427028059959412
epoch = 28/100, loss = 0.1310739368200302
epoch = 29/100, loss = 0.12980657815933228
epoch = 30/100, loss = 0.11612947285175323
epoch = 31/100, loss = 0.12621481716632843
epoch = 32/100, loss = 0.1155557930469513
epoch = 33/100, loss = 0.11612911522388458
epoch = 34/100, loss = 0.1094290092587471
epoch = 35/100, loss = 0.1123606413602829
epoch = 36/100, loss = 0.10296337306499481
epoch = 37/100, loss = 0.09849642962217331
epoch = 38/100, loss = 0.09887552261352539
epoch = 39/100, loss = 0.10212244838476181
epoch = 40/100, loss = 0.10003342479467392
epoch = 41/100, loss = 0.1002800390124321
epoch = 42/100, loss = 0.09632200002670288
epoch = 43/100, loss = 0.08822232484817505
epoch = 44/100, loss = 0.08861575275659561
epoch = 45/100, loss = 0.08913960307836533
epoch = 46/100, loss = 0.08543262630701065
epoch = 47/100, loss = 0.0888872966170311
epoch = 48/100, loss = 0.08676695823669434
epoch = 49/100, loss = 0.08661848306655884
epoch = 50/100, loss = 0.08228827267885208
epoch = 51/100, loss = 0.08091069012880325
epoch = 52/100, loss = 0.08634478598833084
epoch = 53/100, loss = 0.08741255104541779
epoch = 54/100, loss = 0.07282774150371552
epoch = 55/100, loss = 0.07024645060300827
epoch = 56/100, loss = 0.06951993703842163
epoch = 57/100, loss = 0.06997912377119064
epoch = 58/100, loss = 0.06839081645011902
epoch = 59/100, loss = 0.06583476811647415
epoch = 60/100, loss = 0.07030846923589706
epoch = 61/100, loss = 0.0684519112110138
epoch = 62/100, loss = 0.06839233636856079
epoch = 63/100, loss = 0.062250930815935135
epoch = 64/100, loss = 0.06370427459478378
epoch = 65/100, loss = 0.06435031443834305
epoch = 66/100, loss = 0.07280555367469788
epoch = 67/100, loss = 0.06334244459867477
epoch = 68/100, loss = 0.06859203428030014
epoch = 69/100, loss = 0.06077098846435547
epoch = 70/100, loss = 0.06485244631767273
epoch = 71/100, loss = 0.049909766763448715
epoch = 72/100, loss = 0.058882784098386765
epoch = 73/100, loss = 0.052649129182100296
epoch = 74/100, loss = 0.05085344240069389
epoch = 75/100, loss = 0.04926493763923645
epoch = 76/100, loss = 0.048340316861867905
epoch = 77/100, loss = 0.0534214973449707
epoch = 78/100, loss = 0.05051668360829353
epoch = 79/100, loss = 0.04954957589507103
epoch = 80/100, loss = 0.04295102879405022
epoch = 81/100, loss = 0.04586099088191986
epoch = 82/100, loss = 0.04999639838933945
epoch = 83/100, loss = 0.05362413823604584
epoch = 84/100, loss = 0.04375919699668884
epoch = 85/100, loss = 0.042002104222774506
epoch = 86/100, loss = 0.03858386352658272
epoch = 87/100, loss = 0.04003024473786354
epoch = 88/100, loss = 0.03934461995959282
epoch = 89/100, loss = 0.04096955806016922
epoch = 90/100, loss = 0.039348866790533066
epoch = 91/100, loss = 0.03848511353135109
epoch = 92/100, loss = 0.03630184009671211
epoch = 93/100, loss = 0.03543120622634888
epoch = 94/100, loss = 0.033078212291002274
epoch = 95/100, loss = 0.038877565413713455
epoch = 96/100, loss = 0.03456345200538635
epoch = 97/100, loss = 0.03446390479803085
epoch = 98/100, loss = 0.03173131123185158
epoch = 99/100, loss = 0.03642594441771507
epoch = 100/100, loss = 0.030111907050013542

In [21]:
# Model Evaluation 
model.eval()
total = 0
correct = 0

with torch.no_grad():# No gradients to be calculated
    for xb,yb in test_loader:
        outputs = model(xb)
        actul_val, predicted = torch.max(outputs, 1)# Returns Max value in tensors and the index of max value
        correct +=(predicted == yb).sum().item()
        total += yb.size(0) # Actual Samples in each batch
print("total values:", total)
print("Correct:", correct)

total values: 180
Correct: 169

In [23]:
Accuracy = correct/total
print("Accuracy:", Accuracy*100)

Accuracy: 93.88888888888889